### ISSUE TITLE
Cover Art doesn't get downloaded

### ISSUE THREAD

**Issue by cement-head** [fossfreedom/coverart-browser#377]
Ubuntu 12.04.5 LTS; Rhythmbox 2.97 installed from PPA

from terminal

$ rhythmbox

(rhythmbox:5146): Rhythmbox-WARNING **: Could not open device /dev/radio0
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject

(rhythmbox:5146): libpeas-WARNING **: audiocd: /usr/lib/rhythmbox/plugins/audiocd/libaudiocd.so: undefined symbol: discid_get_submission_url

(rhythmbox:5146): libpeas-WARNING **: Could not load plugin module: 'audiocd'

(rhythmbox:5146): libpeas-WARNING **: Error loading plugin 'audiocd'

(rhythmbox:5146): libdmapsharing-WARNING **: Ignoring local service cement_head

(rhythmbox:5146): libdmapsharing-WARNING **: Ignoring local service cement_head

(rhythmbox:5146): libdmapsharing-WARNING **: Ignoring local service cement_head

(rhythmbox:5146): libdmapsharing-WARNING **: Ignoring local service cement_head
Setup Playback Status Listener

(rhythmbox:5146): Gtk-WARNING **: GtkGrid does not have a property called expand

(rhythmbox:5146): Gtk-WARNING **: GtkGrid does not have a property called fill

(rhythmbox:5146): Gtk-WARNING **: GtkGrid does not have a property called position

(rhythmbox:5146): GLib-GObject-CRITICAL **: g_value_get_uint: assertion `G_VALUE_HOLDS_UINT (value)' failed
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/replaygain/player.py", line 159, in playing_entry_changed
    pad.set_blocked_async(True, self.rgvolume_blocked_cb, self.rgvolume)
AttributeError: 'Pad' object has no attribute 'set_blocked_async'

(rhythmbox:5146): GLib-GObject-CRITICAL **: g_value_get_uint: assertion `G_VALUE_HOLDS_UINT (value)' failed
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/replaygain/player.py", line 159, in playing_entry_changed
    pad.set_blocked_async(True, self.rgvolume_blocked_cb, self.rgvolume)
AttributeError: 'Pad' object has no attribute 'set_blocked_async'

(rhythmbox:5146): GLib-GObject-CRITICAL **: g_value_get_uint: assertion `G_VALUE_HOLDS_UINT (value)' failed
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/replaygain/player.py", line 159, in playing_entry_changed
    pad.set_blocked_async(True, self.rgvolume_blocked_cb, self.rgvolume)
AttributeError: 'Pad' object has no attribute 'set_blocked_async'

(rhythmbox:5146): GLib-GObject-CRITICAL **: g_value_get_uint: assertion `G_VALUE_HOLDS_UINT (value)' failed
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/replaygain/player.py", line 159, in playing_entry_changed
    pad.set_blocked_async(True, self.rgvolume_blocked_cb, self.rgvolume)
AttributeError: 'Pad' object has no attribute 'set_blocked_async'

**Comment by fossfreedom** [comment]
I do not see any evidence that coverart browser is running.

The error you see is due to a known issue with 12.04 and RB 2.97 when running replaygain.  You should not use the replaygain plugin with this version of ubuntu.

How have you installed the plugin?
 
From where and what instructions?

When you go to the plugins window is coverart-browser & coverart search ticked?

**Comment by fossfreedom** [comment]
closing - no feedback given.

**Comment by cement-head** [comment]
Coverart-browser is running.  I sent you an email with the screenshot of the plugin running.  If you can't fix, or don't care about fixing your software, I understand.  But feedback was given.

**Comment by fossfreedom** [comment]
No email was received ... I have checked the spam filters and nothing is there. It is best to attach pictures here. Use markdown to point to an imgur uploaded picture.

I am keen to help but I need people to be proactive and respond positively and quickly.

Please add answers to my queries above.

In addition show me the output to

rhythmbox -D coverart

**Comment by cement-head** [comment]
Installed via PPA.

Uninstalled (completely) & reinstalled via PPA.

Was working perfectly up until about a week ago.  Clicking on album
cover that is missing, briefly displays the "Loading..." message and
then **nothing** - almost as if the API between the plugin and the
google search isn'y working properly.

$ rhythmbox

(rhythmbox:7818): Rhythmbox-WARNING **: Could not open
device /dev/radio0

(rhythmbox:7818): libpeas-WARNING **:
audiocd: /usr/lib/rhythmbox/plugins/audiocd/libaudiocd.so: undefined
symbol: discid_get_submission_url

(rhythmbox:7818): libpeas-WARNING **: Could not load plugin module:
'audiocd'

(rhythmbox:7818): libpeas-WARNING **: Error loading plugin 'audiocd'
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning:
g_boxed_type_register_static: assertion `g_type_from_name (name) == 0'
failed
  import gobject._gobject
Setup Playback Status Listener

(rhythmbox:7818): Gtk-WARNING **: GtkGrid does not have a property
called expand

(rhythmbox:7818): Gtk-WARNING **: GtkGrid does not have a property
called fill

(rhythmbox:7818): Gtk-WARNING **: GtkGrid does not have a property
called position

(rhythmbox:7818): GLib-GObject-CRITICAL **: g_value_get_uint: assertion
`G_VALUE_HOLDS_UINT (value)' failed

(rhythmbox:7818): GLib-GObject-CRITICAL **: g_value_get_uint: assertion
`G_VALUE_HOLDS_UINT (value)' failed

**Comment by fossfreedom** [comment]
ok - have now understood where you are having an issue - I'll update the title.

Looks like Google has changed something - it maybe something I cannot fix if Google has removed the album cover search facility :(

If they have, I'll have to disable the capability.  In the interim you can use the cover search capability - define the search providers you want and download the album covers as per the "search preferences" option

 -

**Comment by fossfreedom** [comment]
linked issue:

 - https://github.com/fossfreedom/coverart-browser/issues/137

**Comment by cement-head** [comment]
ok, thanks - understood

**Comment by careca1970** [comment]
Hello!
I have similar problem. I don't know what is meant with "download the album covers as per the "search preferences" option!"

I have some configured internet providers, but in the search window it is gets always shown "Powered by Google".

I can't understand why you linked this issue to an issues from 2013...
It used to work until some days ago...

Please, give instructions on how to get search working back again, even if with out Google.

Many thanks in advance!

**Comment by fossfreedom** [comment]
@careca1970 

 sure - there is a wiki here that explains all.

 - https://github.com/fossfreedom/coverart-browser/wiki/How-to-find-great-coverart

**Comment by careca1970** [comment]
Ok, thanks. But it does not come to close to the results one used to get by Google.
Have you already realised what happened to Google?
Many thanks again!

**Comment by fossfreedom** [comment]
Sorry ... I haven't found the time to look at this.  The linked article refers to the fact that the free api Google provided was going to be removed.  It looks like Google have silently hidden the results rather than removing the api.

I could in theory replace the free api with another Google api ... But that api is not free.  I cannot afford to pay for the service myself :(

As per the wiki, if you don't like the internet providers results, use Firefox or chrome and drag and drop any image you can Google search.

**Comment by careca1970** [comment]
Sure I just realised this. Sad, but this is Google we must live with.
Hope you can find a solution to improve search again.
Nevertheless, your plug-in is still very useful, and a must existing improvement for Rhythmbox!

**Comment by cement-head** [comment]
And...Google has become Microsoft...

**Comment by fossfreedom** [comment]
Hey Guys,

  I've had a quick "google" - I need to research this further, but I may be able to replace the current covers tab in the plugin with a web-page call to the following URL:

https://cse.google.co.uk/cse/publicurl?cx=017866430301960619304:gvpup1fsqc4

I need to find a way of autopopulating the custom search box with the name of the album or artist.

What do you think - is this something useful?

**Comment by fossfreedom** [comment]
second thoughts - no - not useful - whilst the images look ok - they are just thumbnails - you need to click through to get the actual image.

**Comment by fossfreedom** [comment]
looks like duckduckgo image results could work here - example URL:

in python the following could easily be parsed:

 - https://duckduckgo.com/i.js?q=anastacia%sfreak%of%nature&s=50

and the same results can be shown visually:

 - https://duckduckgo.com/?q=anastacia%25sfreak%25of%25nature&s=50&iax=1&ia=images

If anyone is familiar with a bit of javascript/html & python I can help with pointing you in the right direction to make the necessary changes
