### ISSUE TITLE
Can't launch rhythmbox - coverart errors - since 16.04 upgrade

### ISSUE THREAD

**Issue by tenleftfingers** [fossfreedom/coverart-browser#387]
Here's the console output:

$ rhythmbox
/usr/lib/rhythmbox/plugins/coverart_browser/coverart_widgets.py:26: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/rhythmbox/plugins/coverart_browser/coverart_covericonview.py:28: PyGIWarning: PangoCairo was imported without specifying a version first. Use gi.require_version('PangoCairo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import PangoCairo
/usr/lib/rhythmbox/plugins/coverart_browser/coverart_artistinfo.py:28: PyGIWarning: WebKit was imported without specifying a version first. Use gi.require_version('WebKit', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import WebKit
/usr/lib/rhythmbox/plugins/equalizer/Conf.py:20: PyGIWarning: GConf was imported without specifying a version first. Use gi.require_version('GConf', '2.0') before import to ensure that the right version gets loaded.
  from gi.repository import GConf, Gst

(rhythmbox:16731): Gtk-CRITICAL **: gtk_box_pack: assertion '_gtk_widget_get_parent (child) == NULL' failed

(rhythmbox:16731): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist

(rhythmbox:16731): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist

(rhythmbox:16731): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist

(rhythmbox:16731): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist

(rhythmbox:16731): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist

(rhythmbox:16731): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist

(rhythmbox:16731): Gtk-CRITICAL **: gtk_tree_model_filter_iter_parent: assertion 'GTK_TREE_MODEL_FILTER (model)->priv->stamp == child->stamp' failed

(rhythmbox:16731): Gtk-CRITICAL **: gtk_box_reorder_child: assertion 'old_link != NULL' failed
Segmentation fault (core dumped)

**Comment by tenleftfingers** [comment]
Oh, likely a dupe of 386

**Comment by fossfreedom** [comment]
Correct.

**Comment by seanthewebber** [comment]
#386

**Comment by roosnam** [comment]
Hello, just wanted to check if this is open still (just ran into it) and if you plan to get to it any time soon. This is just for my information. Appreciate your time, thanks.

**Comment by nstommel** [comment]
I would love if your application was updated for the new version of Rhythmbox, I miss my album art :(

**Comment by fossfreedom** [comment]
sorry all - don't have the time at the moment to revisit this - happy to help anyone who is willing to pitch in.

**Comment by Dotile** [comment]
Would be happy if you decide to revisit this once you have time. 

The solution in #387 for 16.04 does not work for me on Linux Mint 18 as gir1.2-webkit-3.0 is already on the newest version on my system.

**Comment by BenBenna** [comment]
Yes, would be so happy if you revisited this issue.
Live without coverart-browser is a drag

**Comment by fossfreedom** [comment]
linked https://github.com/fossfreedom/coverart-browser/issues/384

**Comment by gka** [comment]
here's another log, in case it's helpful

```
$ rhythmbox

(rhythmbox:14907): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist

(rhythmbox:14907): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist

(rhythmbox:14907): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist

(rhythmbox:14907): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist

(rhythmbox:14907): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist

(rhythmbox:14907): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist

/usr/lib/rhythmbox/plugins/coverart_browser/coverart_widgets.py:26: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/rhythmbox/plugins/coverart_browser/coverart_covericonview.py:28: PyGIWarning: PangoCairo was imported without specifying a version first. Use gi.require_version('PangoCairo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import PangoCairo

(rhythmbox:14907): libpeas-WARNING **: Error importing plugin 'coverart_browser':
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 890, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/rhythmbox/plugins/coverart_browser/coverart_browser.py", line 32, in <module>
    from coverart_browser_source import CoverArtBrowserSource
  File "/usr/lib/rhythmbox/plugins/coverart_browser/coverart_browser_source.py", line 49, in <module>
    from coverart_artistinfo import ArtistInfoPane
  File "/usr/lib/rhythmbox/plugins/coverart_browser/coverart_artistinfo.py", line 28, in <module>
    from gi.repository import WebKit
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 127, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name WebKit, introspection typelib not found

(rhythmbox:14907): libpeas-WARNING **: Error loading plugin 'coverart_browser'
```

**Comment by insdavm** [comment]
This is also causing #389 to occur on my system.  Rhythmbox crashes when the *Coverart* menu item is clicked on.

* Rhythmbox 3.3
* GTK 3.18.9
* release-2.1 of this plugin

```bash
$ rhythmbox

/usr/lib/rhythmbox/plugins/coverart_browser/coverart_widgets.py:26: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/rhythmbox/plugins/coverart_browser/coverart_covericonview.py:28: PyGIWarning: PangoCairo was imported without specifying a version first. Use gi.require_version('PangoCairo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import PangoCairo
/usr/lib/rhythmbox/plugins/coverart_browser/coverart_artistinfo.py:28: PyGIWarning: WebKit was imported without specifying a version first. Use gi.require_version('WebKit', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import WebKit

(rhythmbox:24631): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist
(rhythmbox:24631): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist
(rhythmbox:24631): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist
(rhythmbox:24631): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist
(rhythmbox:24631): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist
(rhythmbox:24631): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist
(rhythmbox:24631): Gtk-CRITICAL **: gtk_box_reorder_child: assertion 'old_link != NULL' failed

Segmentation fault (core dumped)
```

**Comment by bbrcan** [comment]
@gka I was getting that error, and this worked for me:

`sudo apt install gir1.2-webkit-3.0 `
