### ISSUE TITLE
Load Issue

### ISSUE THREAD

**Issue by colincowie** [fossfreedom/coverart-browser#390]
When I enable the plug in I get the following error:
`(rhythmbox:17954): libpeas-WARNING **: Error importing plugin 'coverart_browser':
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 890, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/rhythmbox/plugins/coverart_browser/coverart_browser.py", line 32, in <module>
    from coverart_browser_source import CoverArtBrowserSource
  File "/usr/lib/rhythmbox/plugins/coverart_browser/coverart_browser_source.py", line 49, in <module>
    from coverart_artistinfo import ArtistInfoPane
  File "/usr/lib/rhythmbox/plugins/coverart_browser/coverart_artistinfo.py", line 28, in <module>
    from gi.repository import WebKit
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 127, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name WebKit, introspection typelib not found

(rhythmbox:17954): libpeas-WARNING **: Error loading plugin 'coverart_browser'
`

I am not sure where I went wrong

**Comment by fossfreedom** [comment]
yep - sorry - the plugin needs all the webkit code to be either removed or upgraded to webkit2.

All recent linux's are affected I'm afraid - I'll close this in favour of this that covers all the issue. https://github.com/fossfreedom/coverart-browser/issues/387
