### ISSUE TITLE
Does not work on Ubuntu 19.04

### ISSUE THREAD

**Issue by mlvtito** [fossfreedom/coverart-browser#399]
At plugin activation on Ubuntu 19.04, this stacktrace appears :

```
(rhythmbox:20078): libpeas-WARNING **: 11:51:11.269: Error importing plugin 'coverart_browser':
Traceback (most recent call last):
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mlvtito/.local/share/rhythmbox/plugins/coverart_browser/coverart_browser.py", line 32, in <module>
    from coverart_browser_source import CoverArtBrowserSource
  File "/home/mlvtito/.local/share/rhythmbox/plugins/coverart_browser/coverart_browser_source.py", line 33, in <module>
    from coverart_album import AlbumManager
  File "/home/mlvtito/.local/share/rhythmbox/plugins/coverart_browser/coverart_album.py", line 1590
    async = rb.Loader()
```

**Comment by mlvtito** [comment]
This issue is linked to pull request #400

**Comment by ghost** [comment]
Vou falar em portugues mesmo. hehehe

eu consegui fazer funcionaaarrr.. ta MUITO SHOWWW!! vejam

![Captura de tela de 2020-08-18 00-26-47](https://user-images.githubusercontent.com/2234645/90467056-c0db4080-e102-11ea-9f83-777aebed2990.png)

eu consegui no PureOS (Debian 100% livre). o que eu fiz foi apenas instalar manualmente o pacote gir1.2-webkit-3.0 e suas dependencias.

eu baixei por aqui:  https://packages.debian.org/stretch/amd64/gir1.2-webkit-3.0/download

e instalei assim

sudo dpkg -i gir1.2-webkit-3.0_2.4.11-3_amd64.deb

tem as dependencias tbm q seguem a mesma parada.
