### ISSUE TITLE
Error importing plugin on Rhythmbox v3.4.3

### ISSUE THREAD

**Issue by ikus060** [fossfreedom/coverart-browser#404]
When trying to import the plugin it failed as follow:.

```
(rhythmbox:1199): libpeas-WARNING **: 08:21:10.925: Error importing plugin 'coverart_browser':
Traceback (most recent call last):
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ikus060/.local/share/rhythmbox/plugins/coverart_browser/coverart_browser.py", line 32, in <module>
    from coverart_browser_source import CoverArtBrowserSource
  File "/home/ikus060/.local/share/rhythmbox/plugins/coverart_browser/coverart_browser_source.py", line 33, in <module>
    from coverart_album import AlbumManager
  File "/home/ikus060/.local/share/rhythmbox/plugins/coverart_browser/coverart_album.py", line 1590
    async = rb.Loader()
          ^
SyntaxError: invalid syntax

(rhythmbox:1199): libpeas-WARNING **: 08:21:10.925: Error loading plugin 'coverart_browser'
```

**Comment by fossfreedom** [comment]
https://github.com/fossfreedom/coverart-browser/issues/403#issuecomment-673023697

**Comment by ghost** [comment]
try this....

https://github.com/fossfreedom/coverart-browser/commit/f8562992d9170599d04da8764422a9fe19ed6fa1
